name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}   
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: black
      run: black --check --diff .
    # - name: Run type check
    #   run: mypy .
    - name: Run flake8
      run: flake8 .
    - name: isort
      run: isort . --check --diff
    - name: Run unit tests
      run: python -m unittest
